Fee warning
baofinance/ui-panda-farms pull request #27
Opened 2021-05-14 03:28 UTC by Vitalsine85

Added fee warnings to modals to improve visibility. Thanks Fabiaz

2021-05-14 03:59 UTC, jondwillis requested changes

2021-05-14 03:59 UTC, jondwillis commented on src/hooks/useBlockDiff.ts
> +  block -
formatting seems odd here, double check it

2021-05-14 03:59 UTC, jondwillis commented on src/hooks/useBlockDiff.ts
> +// import debounce from 'debounce'
rm

2021-05-14 03:59 UTC, jondwillis commented on src/panda/utils.ts
> +    return new BigNumber(0)
it might be better to return null or undefined

2021-05-14 03:59 UTC, jondwillis commented on src/views/Farm/components/Fee.tsx
> +color: red;
formatting looks off in this file-- maybe it is just GitHub

2021-05-14 03:59 UTC, jondwillis commented on src/views/Farm/components/FeeWarning.tsx
> +		)
formatting looks off

2021-05-14 03:59 UTC, jondwillis commented on src/views/Farm/components/WithdrawModal.tsx
> +	pid = 0
maybe better to allow undefined or null and just not show the warning

2021-05-14 03:59 UTC, jondwillis commented on tsconfig.json
> +    "noImplicitAny": false
we probably want this-- did you specifically do it to avoid having to typescript-ify "the edges"?

2021-05-17 14:30 UTC, rocky-baoboa commented on tsconfig.json
> +    "noImplicitAny": false
`noImplicitAny` shouldn't be set, instead you can simply explicitly set something to `any`. 

IE: 

```
function name(arg1: number, arg2) {
  return 1;
}
```

Would throw the `noImplicitAny` error, but you can just do this

```
function name(arg1: number, arg2: any): any {
  return 1;
}
```

2021-05-17 20:05 UTC, Vitalsine85 commented on tsconfig.json
> +    "noImplicitAny": false
thanks for the walkthrough @rocky-baoboa !

2021-05-26 23:58 UTC, jondwillis approved these changes

2021-05-26 23:58 UTC, merged